### ISSUE TITLE
Specific SROs Don't Print Correctly While All Others Do

### ISSUE THREAD

**Issue by Kevin-Bushman** [Vector-98/CleanAPI#32]
SRO0017312 won't print correctly, but all others do.

**Comment by Vector-98** [comment]
![image](https://user-images.githubusercontent.com/64809119/107972422-6fa8ee00-6f79-11eb-8aa1-54501d28a69b.png)

this is the page I get the Location is cut off but I believe that's because its text to large

**Comment by Kevin-Bushman** [comment]
One of your last updates fixed it, I think. Every other SRO would print correctly, but that one wouldn't print any of the line information at all.
