### ISSUE TITLE
Export & Print Buttons Don't Work On SROs Where Line 1 Doesn't Exist

### ISSUE THREAD

**Issue by Kevin-Bushman** [Vector-98/CleanAPI#6]
The "Export" button doesn't work if "Line 1" doesn't exist. The "Print" button also partially breaks.

Example SRO: SRO0009752

**Comment by Kevin-Bushman** [comment]
> 
> 
> The "Export" button doesn't work if "Line 1" doesn't exist. The "Print" button also partially breaks.
> 
> Example SRO: SRO0009752

Actually, the issue(s) happen when any line(s) don't exist.

Example SRO: SRO0009909

**Comment by dlowinske** [comment]
Fixed
