### ISSUE TITLE
Line Buttons For Acer Units Always Only Show 7600

### ISSUE THREAD

**Issue by Kevin-Bushman** [Vector-98/CleanAPI#8]
When viewing an SRO containing Acer units, the line buttons will always only show the ending 7600 of the serial number instead of the relevant last 4 digits.

Example: SRO0009538

Shouldn't be too hard to just strip off the last digits that are always the same and show the relevant last 4 digits instead. Haven't yet looked at the code to verify though.

**Comment by Vector-98** [comment]
Fixed in 1.2.25
